### ISSUE TITLE
Add a way to add quotes from book

### ISSUE THREAD

**Issue by yodatak** [Mozzo1000/booklogr#10]
I love to take some quotes from book and would love to have a tracker app like this to this do this think its in roadmap ?

**Comment by Mozzo1000** [comment]
Hi,
Thank you for your question. I recently added a simple form of note taking, more aimed towards writing down your thoughts and what you felt about a book. Quotes may be something different but I have not thought about this before.
How do you believe a quote differs from a note? Can you describe specific features that are related to quotes or how you would like it to work?

Either way, quotes does sound like it is aligned with this project goals and something that definitely can be added.

**Comment by adamshand** [comment]
Not OP, but I think that notes can be used for quotes.  However, I use quotes and notes quite differently.  I sometimes take extensive quotes from a book and want to record the page number so I can find the original passage again if needed.

Notes are more my personal reflections, or maybe what I use to work up a blog post.  I can see that it might be useful to seperate these out somehow (mostly so I can easily find my notes and not have them lost among a bunch of quotes).

**Comment by Mozzo1000** [comment]
> [...], I use quotes and notes quite differently. I sometimes take extensive quotes from a book and want to record the page number so I can find the original passage again if needed.
> 
> Notes are more my personal reflections, or maybe what I use to work up a blog post. I can see that it might be useful to seperate these out somehow (mostly so I can easily find my notes and not have them lost among a bunch of quotes).

Thank you for sharing your view on what differs between an note and quote. This makes it more clear in my head why quotes needs to be a thing separate from notes. Especially having the page number connected to the quote and have it searchable.                  
I will have to think about how this would work on the frontend...

**Comment by Mozzo1000** [comment]
Ability to add quotes with a page number has now been added. This will be released with version 1.2.0.
The web interface for notes have been renamed to "Notes & Quotes" and there is also a filter if you only want to see quotes.

Thank you @yodatak for the feature request! And thank you @adamshand for helping me understand the request.

![notes_quotes_2](https://github.com/user-attachments/assets/9258dc78-67ef-4038-b817-3f6a8d510cad)
![notes_quotes_1](https://github.com/user-attachments/assets/2ebd6d93-60e4-4449-b111-d959e7346fe5)

**Comment by adamshand** [comment]
Thank you! <3
