### ISSUE TITLE
ActivityPub support?

### ISSUE THREAD

**Issue by adamshand** [Mozzo1000/booklogr#17]
Hey, 

Neat project, thanks!  Would be cool to automatically  have books I've added get posted to my Mastodon/etc account.

Cheers,
Adam.

**Comment by Mozzo1000** [comment]
Hi,
Thank you for your interest in this project. This sounds like a great idea and definitely something I myself would also like to have.
I am thinking we can integrate the mastodon API fairly easily. This would not make this project a fully supported and interoperable actiivtypub server (I have no interest in creating another social media platform) but it would make it able to send out and have you easily share what you reading and what you thought about a specific book.

On an even more technical note, we can listen for certain events and when these events happen we can post a message to the users pre-configured mastodon account.

Events possibly to listen for, 
* Adding book to list X (currently reading or to be read).
* When you finished reading a book.
* When you add a note.
* When you rate a book

**Comment by adamshand** [comment]
That sounds great, thanks!

**Comment by Mozzo1000** [comment]
Sharing to mastodon via events have now been implemented. For now, the worker that will listen in the background will only react when you finish reading a book. It will then toot out a message on the account you have connected. 
More events can be implemented at a later stage.
This feature is opt-in.

Documentation on how to connect booklogr to your mastodon account have been written and can be found in the [wiki ](https://github.com/Mozzo1000/booklogr/wiki/Connect-to-mastodon)

Thank you @adamshand  for your feature request!

**Comment by adamshand** [comment]
Amazing, thank you!
